spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main

  # Global syncPolicy and namespace creation settings (optional)
  syncPolicy: false  # Set to true if automatic sync is desired
  prune: true
  selfHeal: true
  createNamespace: false  # Set to true if namespaces need to be automatically created

applications:
  - name: sealed-secrets
    namespace: kube-system
    helm: true
    syncPolicy: true  # Optional: Override global syncPolicy settings per app

  
  - name: nginx-ingress
    namespace: nginx-ingress
    repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd
    syncPolicy: true  # Optional: Override global syncPolicy settings per app
    prune: false            # Optional: Override syncPolicy settings per app
    createNamespace: true  # Optional: Override namespace creation setting for this app

  - name: cert-manager
    namespace: cert-manager
    
  - name: apache-httpd
    namespace: apache-httpd
    helm: true
    prune: true             # Optional: Override syncPolicy settings per app
    selfHeal: true          # Optional: Override syncPolicy settings per app
    createNamespace: true   # Optional: Override namespace creation setting for this app

  - name: metrics-server
    namespace: kube-system
    repoURL: https://dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd
