spec:
  destination:
    # HIGHLIGHT
    server: https://kubernetes.default.svc
  source:
    # HIGHLIGHT
    repoURL: ${GITOPS_REPO_URL_ARGOCD}
    # HIGHLIGHT
    targetRevision: main

# HIGHLIGHT
applications:
  - name: argocd
  - name: sealed_secrets