spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      createNamespace: false

applications:
  - name: sealed-secrets
    namespace: kube-system
  
  - name: nginx
    namespace: ingress-nginx
    source:
      repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd

  - name: cert-manager
    namespace: cert-manager

  - name: metrics-server
    namespace: kube-system
    source:
      repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd

  - name: strimzi-kafka-operator
    namespace: kafka
    source:
      repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/Strimzi
      targetRevision: master
    appPath: helm/strimzi
