spec:
  destination:
    # HIGHLIGHT
    server: https://kubernetes.default.svc
  source:
    # HIGHLIGHT
    repoURL: https://github.com/GitTactician/app-of-apps
    # HIGHLIGHT
    targetRevision: main

# HIGHLIGHT
applications:
  - name: argocd
    namespace: argocd

charts:
  - name: sealed-secrets
    namespace: kube-system