spec:
  destination:
    # HIGHLIGHT
    server: https://kubernetes.default.svc
  source:
    # HIGHLIGHT
    repoURL: git@ssh.dev.azure.com:v3/cbtw/DevOps/argocd_app_of_apps
    # HIGHLIGHT
    targetRevision: main

# HIGHLIGHT
applications:
  - name: argocd
  - name: sealed-secrets