spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main

applications:
  - name: sealed-secrets
    namespace: kube-system
  
  - name: nginx
    namespace: ingress-nginx
    repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd

  - name: cert-manager
    namespace: cert-manager

  - name: apache-httpd
    namespace: apache-httpd

  - name: metrics-server
    namespace: kube-system
    repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd

  - name: strimzi-kafka-operator
    namespace: kafka
    repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/Strimzi
    appPath: helm/strimzi
    targetRevision: master
