spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main

applications:
  - name: argocd
    namespace: argocd

  - name: sealed-secrets
    namespace: kube-system

  - name: nginx-ingress
    namespace: nginx-ingress

  - name: cert-manager
    namespace: cert-manager

  - name: apache-httpd
    namespace: apache-httpd
