spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main

applications:

  - name: sealed-secrets
    namespace: kube-system
    helm: true

  - name: nginx-ingress
    namespace: nginx-ingress
    helm: false

  - name: cert-manager
    namespace: cert-manager
    helm: false

  - name: apache-httpd
    namespace: apache-httpd
    helm: true
