spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main

applications:
  - name: argocd
    namespace: argocd
    helm: false

  - name: sealed-secrets
    namespace: kube-system
    helm: true

  - name: nginx-ingress
    namespace: nginx-ingress
    helm: false

  - name: nginx-ingress
    namespace: nginx-ingress
    helm: false
