apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc 
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main
    path: app-of-apps
