apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: sealed-secrets
    version: 1.16.0
    repo: https://bitnami-labs.github.io/sealed-secrets
    # Das Release muss ein eindeutiger Name sein, unter dem Helm es installiert
    releaseName: sealed-secrets
    # Falls du Values überschreiben möchtest (lokale values.yaml)
    valuesFile: values.yaml
# patches:
  # HIGHLIGHT
  # - path: deployment-patch.yaml