{{- range .Values.applications }}
  {{- $basePath := .appPath | default "apps" }}
  {{- $repoURL := .repoURL | default $.Values.spec.source.repoURL }}
  {{- $destinationServer := .destinationServer | default $.Values.spec.destination.server }}
  {{- $project := .project | default $.Values.spec.project | default "default" }}
  {{- $targetRevision := .targetRevision | default $.Values.spec.source.targetRevision | default "main" }}
  {{- $syncPolicy := .syncPolicy.automated | default $.Values.spec.syncPolicy.automated | default false }}
  {{- $prune := .syncPolicy.prune | default $.Values.spec.syncPolicy.prune | default false }}
  {{- $selfHeal := .syncPolicy.selfHeal | default $.Values.spec.syncPolicy.selfHeal | default false }}
  {{- $createNamespace := .createNamespace | default false }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ $project }}
  destination:
    server: {{ $destinationServer }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ $basePath }}/{{ .name }}
  {{- if $syncPolicy }}
  syncPolicy:
    automated:
      prune: {{ $prune }}
      selfHeal: {{ $selfHeal }}
    {{- if $createNamespace }}
    syncOptions:
      - CreateNamespace=true
    {{- end }}
  {{- end }}
{{- end }}
