{{- range .Values.applications }}

  {{- $destinationServer := .destinationServer }}
  {{- if not $destinationServer }}
    {{- $destinationServer = $.Values.spec.destination.server }}
  {{- end }}

  # Add project
  {{- $project := .project }}
  {{- if not $project }}
    {{- $project = $.Values.spec.project }}
  {{- end }}
  {{- if not $project }}
    {{- $project = "default" }}
  {{- end }}

  {{- $appSource := .source }}
  {{- if not $appSource }}
    {{- $appSource = $.Values.spec.source }}
  {{- end }}

  {{- $appPath := .name }} # Default fallback is app name if path is not specified
  {{- if $appSource.path }}
    {{- $appPath = printf "%s/%s" $appSource.path .name }}
  {{- else }}
    {{- $appPath = printf "apps/%s" .name }}  # Default path
  {{- end }}

  {{- range $key, $value := $.Values.spec.source }}
    {{- if not (hasKey $appSource $key) }}
      {{- $appSource = merge $appSource (dict $key $value) }}
    {{- end }}
  {{- end }}

  {{- if not $appSource.targetRevision }}
    {{- $appSource = merge $appSource (dict "targetRevision" "main") }}
  {{- end }}

  # Handle syncPolicy with two-level fallback
  {{- $appSyncPolicy := .syncPolicy }}
  {{- if not $appSyncPolicy }}
    {{- $appSyncPolicy = $.Values.spec.syncPolicy }}
  {{- end }}

  {{- if $.Values.spec.syncPolicy }}
    {{- range $key, $value := $.Values.spec.syncPolicy }}
      {{- if not (hasKey $appSyncPolicy $key) }}
        {{- $appSyncPolicy = merge $appSyncPolicy (dict $key $value) }}
      {{- end }}
    {{- end }}
  {{- end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $project }}
  destination:
    server: {{ $destinationServer }}
    namespace: {{ .namespace }}
  source:
    {{- range $key, $value := $appSource }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- if $appSyncPolicy }}
  syncPolicy:
    {{- if $appSyncPolicy.automated }}
    automated:
      prune: {{ default "false" $appSyncPolicy.automated.prune }}
      selfHeal: {{ default "false" $appSyncPolicy.automated.selfHeal }}
    {{- end }}
    {{- if $appSyncPolicy.syncOptions }}
    syncOptions:
      - CreateNamespace={{ default "false" $appSyncPolicy.syncOptions.createNamespace }}
      - DryRun={{ default "false" $appSyncPolicy.syncOptions.dryRun }}
      - PruneLast={{ default "false" $appSyncPolicy.syncOptions.pruneLast }}
      - Replace={{ default "false" $appSyncPolicy.syncOptions.replace }}
      - Validate={{ default "false" $appSyncPolicy.syncOptions.validate }}
      - AllowEmpty={{ default "false" $appSyncPolicy.syncOptions.allowEmpty }}
      - Recreate={{ default "false" $appSyncPolicy.syncOptions.recreate }}
    {{- end }}
  {{- end }}
{{- end }}
