{{- range .Values.applications }}
  # Determine appPath with fallback
  {{- $basePath := .appPath }}
  {{- if not $basePath }}
    {{- $basePath = "apps" }}
  {{- end }}
  {{- $appPath := printf "%s/%s" $basePath .name }}

  # Handle Helm configuration and other parameters
  {{- $isHelm := .helm }}
  {{- $repoURL := .repoUrl }}
  {{- if not $repoURL }}
    {{- $repoURL = $.Values.spec.source.repoURL }}
  {{- end }}
  {{- $targetRevision := .targetRevision }}
  {{- if not $targetRevision }}
    {{- $targetRevision = $.Values.spec.source.targetRevision }}
  {{- end }}
  # Handle syncPolicy with fallback
  {{- $syncPolicy := .syncPolicy }}
  {{- if not $syncPolicy }}
    {{- $syncPolicy = $.Values.spec.syncPolicy }}
  {{- end }}

  {{- $prune := .prune }}
  {{- if not $prune }}
    {{- $prune = $.Values.spec.syncPolicy.automated.prune }}
  {{- end }}

  {{- $selfHeal := .selfHeal }}
  {{- if not $selfHeal }}
    {{- $selfHeal = $.Values.spec.syncPolicy.automated.selfHeal }}
  {{- end }}

  {{ $createNamespace := .createNamespace }}
  {{- if not $createNamespace }}
    {{- $createNamespace = $.Values.spec.createNamespace }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ $appPath }}
    {{- if $isHelm eq true }}
    helm:
      releaseName: {{ .name }}
    {{- end }}
  {{- if $syncPolicy}}
  syncPolicy:
    {{- if not $prune and not $selfHeal }}
    automated: {}
    {{- end }}
    {{- if $prune and not $selfHeal }}
    automated:
        prune: {{ $prune }}
    {{- end }}
    {{- if not $prune and $selfHeal }}
    automated:
        selfHeal: {{ $selfHeal }}
    {{- end }}
    {{- if $prune and $selfHeal }}
    automated:
        prune: {{ $prune }}
        selfHeal: {{ $selfHeal }}
    {{- end }}
    {{- if $createNamespace }}
  syncOptions:
    - CreateNamespace=true
    {{- end }}
  {{- end}}
  {{- if not $syncPolicy }}
  syncPolicy: {}
  {{- end }}
{{- end }}
