{{- range .Values.applications }}
  # Determine appPath with fallback
  {{- $basePath := .appPath }}
  {{- if not $basePath }}
    {{- $basePath = "apps" }}
  {{- end }}
  {{- $appPath := printf "%s/%s" $basePath .name }}

  # Handle Helm configuration and other parameters
  {{- $isHelm := .helm }}
  {{- $repoURL := .repoUrl }}
  {{- if not $repoURL }}
    {{- $repoURL = $.Values.spec.source.repoURL }}
  {{- end }}
  {{- $targetRevision := .targetRevision }}
  {{- if not $targetRevision }}
    {{- $targetRevision = $.Values.spec.source.targetRevision }}
  {{- end }}
  # Handle syncPolicy with fallback
  {{- $syncPolicy := .syncPolicy }}
  {{- if not $syncPolicy }}
    {{- $syncPolicy = $.Values.spec.syncPolicy }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ $appPath }}
    {{- if $isHelm }}
    helm:
      releaseName: {{ .name }}
    {{- end }}
  {{- if $syncPolicy}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  {{- end}}
  {{- if not $syncPolicy }}
  syncPolicy: {}
  {{- end }}
{{- end }}
