{{- range .Values.applications }}
{{- $appPath := printf "apps/%s" .name }}

{{- $isHelm := false }}
{{- if isFile printf("%s./myfile" .name) }}
{{- $isHelm = true }}
{{- end }})}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    {{- if $isHelm }}
    helm:
      releaseName: {{ .name }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $appPath }}
    {{- else }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $appPath }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
