{{- range .Values.applications }}
  # Define default values and allow overrides using explicit if conditions
  {{- $basePath := .path }}
  {{- if not $basePath }}
    {{- $basePath = "apps" }}
  {{- end }}
  {{- $appPath := printf "%s/%s" $basePath .name }}

  {{- $appRepoURL := .repoURL }}
  {{- if not $appRepoURL }}
    {{- $appRepoURL = $.Values.spec.source.repoURL }}
  {{- end }}

  {{- $appTargetRevision := .targetRevision }}
  {{- if not $appTargetRevision }}
    {{- $appTargetRevision = $.Values.spec.source.targetRevision }}
  {{- end }}
  {{- if not $appTargetRevision }}
    {{- $appTargetRevision = "main" }}
  {{- end }}

  {{- $appNamespaceCreation := .namespaceCreation }}
  {{- if not $appNamespaceCreation }}
    {{- $appNamespaceCreation = $.Values.spec.namespaceCreation }}
  {{- end }}
  {{- if not $appNamespaceCreation }}
    {{- $appNamespaceCreation = false }}
  {{- end }}

  {{- $appSyncAutomated := .syncPolicy.automated }}
  {{- if not $appSyncAutomated }}
    {{- $appSyncAutomated = false }}
  {{- end }}

  {{- $appSyncPrune := .syncPolicy.prune }}
  {{- if not $appSyncPrune }}
    {{- $appSyncPrune = false }}
  {{- end }}

  {{- $appSyncSelfHeal := .syncPolicy.selfHeal }}
  {{- if not $appSyncSelfHeal }}
    {{- $appSyncSelfHeal = false }}
  {{- end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project }}
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $appRepoURL }}
    targetRevision: {{ $appTargetRevision }}
    path: {{ $appPath }}
    {{- if .helm }}
    helm:
      releaseName: {{ .name }}
    {{- end }}
  syncPolicy:
    {{- if $appSyncAutomated }}
    automated:
      prune: {{ $appSyncPrune }}
      selfHeal: {{ $appSyncSelfHeal }}
    {{- if $appNamespaceCreation }}
    syncOptions:
      - CreateNamespace= {{$appNamespaceCreation}}
    {{- end }}
    {{- else }}
    {}
    {{- end }}
{{- end }}
