{{- range .Values.applications }}
  {{- $appPath := printf "app-of-apps/apps/%s" .name }}
  {{- $helmPath := printf "app-of-apps/apps/%s/Chart.yaml" .name }}
  {{- $isHelm := false }}

  # Check if Chart.yaml exists in the app folder by path
  {{- if .Files.Get $helmPath }}
    {{- $isHelm = true }}
  {{- end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    {{- if $isHelm }}
    helm:
      releaseName: {{ .name }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $appPath }}
    {{- else }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $appPath }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
