{{- range .Values.applications }}
  # Define default values and allow overrides
  {{- $basePath := .path | default "apps" }}
  {{- $appPath := printf "%s/%s" $basePath .name }}
  {{- $appRepoURL := .repoURL | default $.Values.spec.source.repoURL }}
  {{- $appTargetRevision := .targetRevision | $.Values.spec.source.targetRevision | default "main" }}
  {{- $appSyncAutomated := .syncPolicy.automated | $.Values.spec.syncPolicy.automated | default false }}
  {{- $appSyncPrune := .syncPolicy.prune | $.Values.spec.syncPolicy.prune | default false }}
  {{- $appSyncSelfHeal := .syncPolicy.selfHeal | $.Values.spec.syncPolicy.selfHeal | default false }}
  {{- $appNamespaceCreation := .namespaceCreation | $.Values.spec.namespaceCreation | default false }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
    {{- if $appNamespaceCreation }}
    namespaceCreation: true
    {{- end }}
  source:
    repoURL: {{ $appRepoURL }}
    targetRevision: {{ $appTargetRevision }}
    path: {{ $appPath }}
    {{- if .helm }}
    helm:
      releaseName: {{ .name }}
    {{- end }}
  syncPolicy:
    {{- if $appSyncAutomated }}
    automated:
      prune: {{ $appSyncPrune }}
      selfHeal: {{ $appSyncSelfHeal }}
    {{- else }}
    automated: false
    {{- end }}
{{- end }}
