{{- range .Values.applications }}
  # Determine appPath with fallback
  {{- $basePath := .appPath }}
  {{- if not $basePath }}
    {{- $basePath = "apps" }}
  {{- end }}
  {{- $appPath := printf "%s/%s" $basePath .name }}

  # Handle Helm configuration and other parameters
  {{- $isHelm := .helm }}
  {{- $repoURL := .repoUrl }}
  {{- if not $repoURL }}
    {{- $repoURL = $.Values.spec.source.repoURL }}
  {{- end }}
  {{- $targetRevision := .targetRevision }}
  {{- if not $targetRevision }}
    {{- $targetRevision = $.Values.spec.source.targetRevision }}
  {{- end }}

  # Handle syncPolicy with fallback
  {{- $syncPolicy := .syncPolicy }}
  {{- if not $syncPolicy }}
    {{- $syncPolicy = $.Values.spec.syncPolicy }}
  {{- end }}

  {{- $prune := .prune }}
  {{- if not $prune }}
    {{- $prune = $.Values.spec.syncPolicy.automated.prune }}
  {{- end }}

  {{- $selfHeal := .selfHeal }}
  {{- if not $selfHeal }}
    {{- $selfHeal = $.Values.spec.syncPolicy.automated.selfHeal }}
  {{- end }}

  {{- $createNamespace := .createNamespace }}
  {{- if not $createNamespace }}
    {{- $createNamespace = $.Values.spec.createNamespace }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ $appPath }}
    {{- if eq $isHelm true }}
    helm:
      releaseName: {{ .name }}
    {{- end }}

  {{- if and $syncPolicy (eq $syncPolicy true) }}
  syncPolicy:
    automated:
      {{- if and $prune (eq $prune true) }}
      prune: {{ $prune }}
      {{- end }}
      {{- if and $selfHeal (eq $selfHeal true) }}
      selfHeal: {{ $selfHeal }}
      {{- end }}
    {{- if eq $createNamespace true }}
    syncOptions:
      - CreateNamespace=true
    {{- end }}
  {{- else }}
  syncPolicy: {}
  {{- end }}
{{- end }}
