{{- range .Values.applications }}
  # Determine appPath with fallback
  {{- $basePath := .appPath }}
  {{- if not $basePath }}
    {{- $basePath = "apps" }}
  {{- end }}
  {{- $appPath := printf "%s/%s" $basePath .name }}

  # Handle repoURL with fallback
  {{- $repoURL := .repoURL }}
  {{- if not $repoURL }}
    {{- $repoURL = $.Values.spec.source.repoURL }}
  {{- end }}

  # add destination server
  {{- $destinationServer := .destinationServer }}
  {{- if not $destinationServer }}
    {{- $destinationServer = $.Values.spec.destination.server }}
  {{- end }}

  # add project
  {{- $project := .project }}
  {{- if not $project }}
    {{- $project = $.Values.spec.project }}
  {{- end }}
  {{- if not $project }}
    {{- $project = "default" }}
  {{- end }}

  # Handle targetRevision with fallback
  {{- $targetRevision := .targetRevision }}
  {{- if not $targetRevision }}
    {{- $targetRevision = $.Values.spec.source.targetRevision }}
  {{- end }}
  {{- if not $targetRevision }}
    {{- $targetRevision = "main" }}  # Default to 'main' if no targetRevision
  {{- end }}

  # Handle syncPolicy with fallback
  {{- $syncPolicy := true }}

  {{- if not .syncPolicy }}
    {{- $syncPolicy = false}}
  {{- end }}

  {{- if eq $syncPolicy true }}
    {{- if not $.Values.spec.syncPolicy }}
      {{- $syncPolicy = false }}
    {{- end }}
  {{- end }}

  # Prune default logic: If prune is not set, default to false
  {{- $prune := .prune }}
  {{- if not $prune }}
    {{- $prune = false }}
  {{- end }}

  # SelfHeal default logic: If selfHeal is not set, default to false
  {{- $selfHeal := .selfHeal }}
  {{- if not $selfHeal }}
    {{- $selfHeal = false }}
  {{- end }}

  # CreateNamespace default logic: If createNamespace is not set, default to false
  {{- $createNamespace := .syncPolicy.createNamespace }}
  {{- if not $createNamespace }}
    {{- $createNamespace = false }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ $project }}
  destination:
    server: {{ $destinationServer }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ $appPath }}
  {{- if eq $syncPolicy true }}
  syncPolicy:
    automated:
      prune: {{ $prune }}
      selfHeal: {{ $selfHeal }}
    {{- if eq $createNamespace true }}
    syncOptions:
      - CreateNamespace=true
    {{- end }}
  {{- end }}
{{- end }}