{{- range .Values.applications }}
  # Define default values and allow overrides

  {{- $basePath := .path }}
  {{- if not $basePath }}
    {{- $basePath = "apps" }}
  {{- end }}
  {{- $appPath := printf "%s/%s" $basePath .name }}
  
  {{- $appRepoURL := .repoURL }}
  {{- if not $appRepoURL }}
    {{- $appRepoURL = $.Values.spec.source.repoURL }}
  {{- end }}
  
  {{- if .targetRevision }}
    {{- $appTargetRevision := .targetRevision }}
  {{- else }}
    {{- if $.Values.spec.source.targetRevision }}
      {{- $appTargetRevision := $.Values.spec.source.targetRevision }}
    {{- else }}
      {{- $appTargetRevision := "main" }}
    {{- end }}
  {{- end }}

  {{- if .syncPolicy }}
    {{- if .syncPolicy.automated }}
      {{- $appSyncAutomated := .syncPolicy.automated }}
    {{- else }}
      {{- $appSyncAutomated := $.Values.spec.syncPolicy.automated | default false }}
    {{- end }}
    {{- $appSyncPrune := .syncPolicy.prune | default $.Values.spec.syncPolicy.prune | default false }}
    {{- $appSyncSelfHeal := .syncPolicy.selfHeal | default $.Values.spec.syncPolicy.selfHeal | default false }}
  {{- else }}
    {{- $appSyncAutomated := $.Values.spec.syncPolicy.automated | default false }}
    {{- $appSyncPrune := $.Values.spec.syncPolicy.prune | default false }}
    {{- $appSyncSelfHeal := $.Values.spec.syncPolicy.selfHeal | default false }}
  {{- end }}
  
  {{- $appNamespaceCreation := .namespaceCreation }}
  {{- if not $appNamespaceCreation }}
    {{- $appNamespaceCreation = $.Values.spec.namespaceCreation | default false }}
  {{- end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
    {{- if $appNamespaceCreation }}
    namespaceCreation: true
    {{- end }}
  source:
    repoURL: {{ $appRepoURL }}
    targetRevision: {{ $appTargetRevision }}
    path: {{ $appPath }}
    {{- if .helm }}
    helm:
      releaseName: {{ .name }}
    {{- end }}
  syncPolicy:
    {{- if $appSyncAutomated }}
    automated:
      prune: {{ $appSyncPrune }}
      selfHeal: {{ $appSyncSelfHeal }}
    {{- else }}
    automated: false
    {{- end }}
{{- end }}
