{{- range .Values.applications }}
  {{- $appPath := printf "apps/%s" .name }}
  {{- $chartPath := printf "apps/%s/charts/Chart.yaml" .name }}

  # Attempt to get the Chart.yaml file content
  {{- with .Files.Get $chartPath }}
    {{- $hasHelmChart := true }}
  {{- else }}
    {{- $hasHelmChart := false }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  source:
    {{- if $isHelm }}
    helm:
      releaseName: {{ .name }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $appPath }}
    {{- else }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $appPath }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
