{{- range .Values.applications }}
  # Determine appPath with fallback
  # {{- $basePath := .appPath }}
  # {{- if not $basePath }}
  #   {{- $basePath = "apps" }}
  # {{- end }}
  # {{- $appPath := printf "%s/%s" $basePath .name }}

  # Add destination server
  {{- $destinationServer := .destinationServer }}
  {{- if not $destinationServer }}
    {{- $destinationServer = $.Values.spec.destination.server }}
  {{- end }}

  # Add project
  {{- $project := .project }}
  {{- if not $project }}
    {{- $project = $.Values.spec.project }}
  {{- end }}
  {{- if not $project }}
    {{- $project = "default" }}
  {{- end }}

  {{- $appSource := .source }}
  {{- if not $appSource }}
    {{- $appSource = $.Values.spec.source }}
  {{- end }}

  # Handle syncPolicy with two-level fallback
  {{- $appSyncPolicy := .syncPolicy }}
  {{- if not $appSyncPolicy }}
    {{- $appSyncPolicy = $.Values.spec.syncPolicy }}
  {{- end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ $project }}
  destination:
    server: {{ $destinationServer }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ $appSource.repoURL }}
    targetRevision: {{ default "main" $appSource.targetRevision }}
    path: {{ default {{ printf "apps/%s" .name }} {{ printf "%s/%s" $appSource.path .name }} }}
  {{- if $appSyncPolicy }}
  syncPolicy:
    automated:
      prune: {{ default "false" $appSyncPolicy.automated.prune }}
      selfHeal: {{ default "false" $appSyncPolicy.automated.selfHeal }}
    {{- if $appSyncPolicy.syncOptions }}
    syncOptions:
      - CreateNamespace={{ default "false" $appSyncPolicy.syncOptions.createNamespace }}
    {{- end }}
  {{- end }}
{{- end }}
