spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/app-of-apps
    targetRevision: main
  createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

applications:
  - name: sealed-secrets
    namespace: kube-system
    helm: true
    appPath: apps/sealed-secrets
    targetRevision: v1.0.0
    syncPolicy: true
    prune: true
    selfHeal: true
    createNamespace: false

  - name: nginx-ingress
    namespace: nginx-ingress
    helm: false
    appPath: apps/nginx-ingress
    targetRevision: v2.1.0
    syncPolicy: false
    prune: false
    selfHeal: false
    createNamespace: true

  - name: cert-manager
    namespace: cert-manager
    helm: true
    appPath: apps/cert-manager
    targetRevision: v3.2.0
    syncPolicy: true
    prune: true
    selfHeal: false
    createNamespace: true

  - name: apache-httpd
    namespace: apache-httpd
    helm: false
    appPath: apps/apache-httpd
    targetRevision: main
    syncPolicy: false
    prune: true
    selfHeal: true
    createNamespace: false
