apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# taken from https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.2/manifests/ha/install.yaml
resources:
- argocd.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
    data:
      # we use annotations for tracking ownership because this avoids certain compatibility problems
      application.resourceTrackingMethod: annotation

namespace: argocd